kind: Service
apiVersion: v1
metadata:
  name: qotd-image
  labels:
    app: qotd
    tier: api
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"qotd","tier":"api"},"name":"qotd-image","namespace":"qotd"},"spec":{"ports":[{"name":"http","port":3003,"protocol":"TCP","targetPort":3003}],"selector":{"app":"qotd-image"},"type":"ClusterIP"}}

spec:
  ports:
    - name: http
      protocol: TCP
      port: 3003
      targetPort: 3003
  selector:
    app: qotd-image

  type: NodePort

status:
  loadBalancer: {}
