kind: Service
apiVersion: v1
metadata:
  name: qotd-db
  namespace: qotd
  labels:
    app: qotd-db
    tier: data
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"qotd-db","tier":"data"},"name":"qotd-db","namespace":"qotd"},"spec":{"ports":[{"name":"mysql","port":3306,"protocol":"TCP","targetPort":3306}],"selector":{"app":"qotd-db"},"type":"ClusterIP"}}

spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: qotd-db

  type: NodePort

status:
  loadBalancer: {}
