kind: Service
apiVersion: v1
metadata:
  name: qotd-rating
  namespace: qotd
  labels:
    app: qotd
    tier: api
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"qotd","tier":"api"},"name":"qotd-rating","namespace":"qotd"},"spec":{"ports":[{"name":"http","port":3004,"protocol":"TCP","targetPort":3004}],"selector":{"app":"qotd-rating"},"type":"ClusterIP"}}

spec:
  ports:
    - name: http
      protocol: TCP
      port: 3004
      targetPort: 3004
  selector:
    app: qotd-rating
  type: NodePort

status:
  loadBalancer: {}
