kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"qotd","tier":"api"},"name":"qotd-ratings","namespace":"qotd"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"qotd-rating"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"qotd-rating"}},"spec":{"containers":[{"env":[{"name":"INSTANA_AGENT_HOST","valueFrom":{"fieldRef":{"fieldPath":"status.hostIP"}}},{"name":"LOG_LEVEL","value":"DEBUG"},{"name":"ENABLE_INSTANA","value":"true"},{"name":"ANOMALY_GENERATOR_URL","value":"http://qotd-usecase.qotd-usecase.svc.cluster.local:3012/services/ratings"},{"name":"POLLING_FREQUENCY","value":"5000"}],"image":"jp.icr.io/qotd/qotd-ratings:v1.0","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":3004,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"name":"qotd-rating","ports":[{"containerPort":3004,"name":"http","protocol":"TCP"}],"resources":{"limits":{"cpu":"200m","memory":"200Mi"},"requests":{"cpu":"25m","memory":"40Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"registry-secret"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  resourceVersion: '2673230'
  name: qotd-ratings

  namespace: qotd
  labels:
    app: qotd
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotd-rating
  template:
    metadata:
      labels:
        app: qotd-rating
    spec:
      containers:
        - resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 25m
              memory: 40Mi
          terminationMessagePath: /dev/termination-log
          name: qotd-rating
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: INSTANA_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: LOG_LEVEL
              value: DEBUG
            - name: ENABLE_INSTANA
              value: 'true'
            - name: ANOMALY_GENERATOR_URL
              value: >-
                http://qotd-usecase.qotd-usecase.svc.cluster.local:3012/services/ratings
            - name: POLLING_FREQUENCY
              value: '5000'
          ports:
            - name: http
              containerPort: 3004
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'jp.icr.io/qotd/qotd-ratings:v1.0'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: registry-secret
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-04-07T08:01:09Z'
      lastTransitionTime: '2022-04-07T08:01:09Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-04-07T08:01:09Z'
      lastTransitionTime: '2022-04-07T08:01:04Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "qotd-ratings-7d9b557cbd" has successfully progressed.
