kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '4'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"qotd","tier":"api"},"name":"qotd-engraving","namespace":"qotd"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"qotd-engraving"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"qotd-engraving"}},"spec":{"containers":[{"env":[{"name":"INSTANA_AGENT_HOST","valueFrom":{"fieldRef":{"fieldPath":"status.hostIP"}}},{"name":"LOG_LEVEL","value":"DEBUG"},{"name":"ENABLE_INSTANA","value":"true"},{"name":"ANOMALY_GENERATOR_URL","value":"http://qotd-usecase.qotd-usecase.svc.cluster.local:3012/services/engraving"},{"name":"POLLING_FREQUENCY","value":"5000"},{"name":"SUPPLY_CHAIN_URL","value":""},{"name":"SUPPLY_CHAIN_SIMULATE","value":"true"}],"image":"jp.icr.io/qotd/qotd-engraving:v1.0","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":3006,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"name":"qotd-engraving","ports":[{"containerPort":3006,"name":"http","protocol":"TCP"}],"resources":{"limits":{"cpu":"200m","memory":"200Mi"},"requests":{"cpu":"25m","memory":"40Mi"}},"terminationMessagePath":"/dev/termination-log"}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"registry-secret"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  resourceVersion: '2660345'
  name: qotd-engraving

  namespace: qotd
  labels:
    app: qotd
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotd-engraving
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qotd-engraving
    spec:
      containers:
        - resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 25m
              memory: 40Mi
          terminationMessagePath: /dev/termination-log
          name: qotd-engraving
          livenessProbe:
            httpGet:
              path: /health
              port: 3006
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: INSTANA_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: LOG_LEVEL
              value: DEBUG
            - name: ENABLE_INSTANA
              value: 'true'
            - name: ANOMALY_GENERATOR_URL
              value: >-
                http://qotd-usecase.qotd-usecase.svc.cluster.local:3012/services/engraving
            - name: POLLING_FREQUENCY
              value: '5000'
            - name: SUPPLY_CHAIN_URL
            - name: SUPPLY_CHAIN_SIMULATE
              value: 'true'
          ports:
            - name: http
              containerPort: 3006
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'jp.icr.io/qotd/qotd-engraving:v1.0'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: registry-secret
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 4
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-04-07T07:21:02Z'
      lastTransitionTime: '2022-04-07T07:21:02Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-04-07T07:53:18Z'
      lastTransitionTime: '2022-04-07T01:27:07Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "qotd-engraving-7dccdfd975" has successfully progressed.
