kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '4'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"qotd","tier":"api"},"name":"qotd-image","namespace":"qotd"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"qotd-image"}},"template":{"metadata":{"labels":{"app":"qotd-image"}},"spec":{"containers":[{"env":[{"name":"INSTANA_AGENT_HOST","valueFrom":{"fieldRef":{"fieldPath":"status.hostIP"}}},{"name":"LOG_LEVEL","value":"DEBUG"},{"name":"ENABLE_INSTANA","value":"true"},{"name":"ANOMALY_GENERATOR_URL","value":"http://qotd-usecase.qotd-usecase.svc.cluster.local:3012/services/image"},{"name":"POLLING_FREQUENCY","value":"5000"}],"image":"jp.icr.io/qotd/qotd-image:v1.0","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/health","port":3003},"initialDelaySeconds":10,"periodSeconds":5},"name":"qotd-image","ports":[{"containerPort":3003,"name":"http","protocol":"TCP"}],"resources":{"limits":{"cpu":"200m","memory":"800Mi"},"requests":{"cpu":"25m","memory":"200Mi"}}}],"imagePullSecrets":[{"name":"registry-secret"}],"restartPolicy":"Always"}}}}
  resourceVersion: '2660853'
  name: qotd-image

  namespace: qotd
  labels:
    app: qotd
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotd-image
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qotd-image
    spec:
      containers:
        - resources:
            limits:
              cpu: 200m
              memory: 800Mi
            requests:
              cpu: 25m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          name: qotd-image
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: INSTANA_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: LOG_LEVEL
              value: DEBUG
            - name: ENABLE_INSTANA
              value: 'true'
            - name: ANOMALY_GENERATOR_URL
              value: >-
                http://qotd-usecase.qotd-usecase.svc.cluster.local:3012/services/image
            - name: POLLING_FREQUENCY
              value: '5000'
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'jp.icr.io/qotd/qotd-image:v1.0'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: registry-secret
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 4
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-04-07T07:44:11Z'
      lastTransitionTime: '2022-04-07T07:44:11Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-04-07T07:53:35Z'
      lastTransitionTime: '2022-04-07T01:26:20Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "qotd-image-65d7db784b" has successfully progressed.
